### ISSUE TITLE
Configurable severities

### ISSUE THREAD

**Issue by swiebertje** [PMudra/ApiCheck#12]
We're using ApiCheck in a large project where we check the backwards compatibility for ~20 API assemblies. The ignore list is convenient enough for us to control API breaking changes but we would like to be able to configure what kind of changes are reported as an error.

For example we don't really care about parameter name changes and we would therefore want to mark it as warning instead of error.

Would it be okay to add such a configuration to ApiCheck? I'm willing to create a PR for this.

**Comment by PMudra** [comment]
Yes, please go ahead! I am happy that somebody is using and extending the tool :smile: 

How do you use ApiCheck? By using the library, console app or the nunit integration? I was not quite sure what the best approach was when I first started the project.

Just some notes about the configuration:

The ignore configuration is very basic and might be extended also. Maybe you can design a new configuration file / object that supports more features. I am thinking about a YAML file like this:

```yml
ignore:
  - MyCompany.MyNamespace.MyClass # ignore MyClass becaus it changed a lot
checks:
  ChangedParameterName: waring # globally set the check for changed parameter names to warning
classes:
  - MyCompany.MyNamespace.MyOtherClass:
      ignore:
        - MyMethod # ignore the absence of MyMethod 
      checks:
        MissingProperty: warning # set missing property to waring because it is okay in this class for some reason
```

This is just an idea. Please feel free to implement the feature as you like.
